version: 2
jobs:
  build:
    working_directory: ~/pakisita
    docker:
      - image: cimg/android:2022.12.1-ndk
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
      RUST_VERSION: 1.67.0
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
      - run:
          name: Update environment variables
          command: |
            echo 'export PATH="$HOME"/.cargo/bin:"$PATH"' >> "$BASH_ENV"
      - run: rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleRelease check -PCARGO_PROFILE=release
      - store_artifacts:
          path: mobile/build/outputs/apk
          destination: apk/mobile
